#!/usr/bin/env node
/**
 * generate-stats.mjs — Compute SSOT stats for Synapse facts.
 * Outputs docs/public/synapse-stats.yaml.
 * Run by maintainers manually or in CI prebuild.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

function listAgents() {
  const modulesDir = join(ROOT, 'modules');
  const allAgentFiles = [];
  const byModule = {};
  for (const m of readdirSync(modulesDir)) {
    const agentDir = join(modulesDir, m, 'agents');
    if (!statSync(agentDir, { throwIfNoEntry: false })?.isDirectory()) continue;
    const files = readdirSync(agentDir).filter(f => f.endsWith('.md'));
    byModule[m] = files.length;
    files.forEach(f => allAgentFiles.push({ module: m, name: f.replace(/\.md$/, '') }));
  }
  // unique by name
  const uniqueIds = new Set(allAgentFiles.map(a => a.name));
  return {
    total_files: allAgentFiles.length,
    total_unique: uniqueIds.size,
    by_module: byModule,
  };
}

function listModules() {
  const modulesDir = join(ROOT, 'modules');
  const dirs = readdirSync(modulesDir).filter(m => statSync(join(modulesDir, m)).isDirectory());
  return { total: dirs.length, list: dirs };
}

function listPresets() {
  const presetsDir = join(ROOT, 'presets');
  try {
    return readdirSync(presetsDir).filter(p => p.endsWith('.yaml')).length;
  } catch { return 0; }
}

const VERSION = readFileSync(join(ROOT, 'VERSION'), 'utf8').trim();
const agents = listAgents();
const modules = listModules();
const presets = listPresets();

const yaml = `# Synapse SSOT Stats — Auto-generated, DO NOT EDIT
# Generated by scripts/generate-stats.mjs
version: "${VERSION}"
generated_at: "${new Date().toISOString()}"

agents:
  total_unique: ${agents.total_unique}
  total_files: ${agents.total_files}
  by_module:
${Object.entries(agents.by_module).map(([k, v]) => `    ${k}: ${v}`).join('\n')}

modules:
  total: ${modules.total}
  list:
${modules.list.map(m => `    - ${m}`).join('\n')}

presets:
  total: ${presets}

# Consumers:
# - lysander-bond: scripts/sync_from_core.mjs pulls this file
# - lysander-bond pages reference {stats.agents.total_unique} not hardcoded numbers
# - audit_facts.py weekly cron compares this to all repos
`;

writeFileSync(join(ROOT, 'docs/public/synapse-stats.yaml'), yaml);
console.log(`✓ docs/public/synapse-stats.yaml updated`);
console.log(`  agents: ${agents.total_unique} unique / ${agents.total_files} files`);
console.log(`  modules: ${modules.total}`);
console.log(`  presets: ${presets}`);
